### ISSUE TITLE
AsyncioSelectorReactor.run removed

### ISSUE THREAD

**Issue by stav** [itamarst/txtulip#4]
I'm not sure why but I have to comment out [self._asyncioEventloop.run_forever()](https://github.com/itamarst/txtulip/blob/master/txtulip/reactor.py#L105) from the `run` method to get my install to work.  Otherwise my server needs an interrupt to get it to finish loading and also cannot be shutdown with a subsequent interrupt because it says:

	Traceback (most recent call last):
	  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
	    self._callback(*self._args)
	  File "/home/stav/Work/SH/Scrapybox/scrapybox/txtulip/reactor.py", line 138, in <lambda>
	    g = lambda: f(*args, **kwargs)
	  File "/home/stav/Work/SH/Scrapybox/scrapybox/txtulip/reactor.py", line 109, in stop
	    PosixReactorBase.stop(self)
	  File "/home/stav/.virtualenvs/scrapybox/lib/python3.5/site-packages/twisted/internet/base.py", line 581, in stop
	    "Can't stop reactor that isn't running.")
	twisted.internet.error.ReactorNotRunning: Can't stop reactor that isn't running.

So then I have to kill the process.

But if I comment out that run method everything works fine.

My implementation is: https://github.com/stav/scrapybox/blob/master/txtulip/reactor.py#L104

**Comment by itamarst** [comment]
Huh, I had no idea anyone was using this. I'll see if I have some time in next few weeks to take a look. Alternatively if you could provide a PR with a test case that would be helpful.
